enabled: true
stats:
  health: 40.0

armor:
  helmet: "NETHERITE_HELMET"
  chestplate: "NETHERITE_CHESTPLATE"
  leggings: "NETHERITE_LEGGINGS"
  boots: "NETHERITE_BOOTS"

items:
  weapon_slot: 8
  weapon: "NETHERITE_SWORD"
  skill1_slot: 1
  skill1: "PAPER"
  skill2_slot: 2
  skill2: "PAPER"
  skill3_slot: 3
  skill3: "PAPER"
  skill4_slot: 4
  skill4: "PAPER"

triggers:
  skill_1: "INTERACT:skill1"
  skill_2: "INTERACT:skill2"
  skill_3: "INTERACT:skill3"
  skill_4: "INTERACT:skill4"
