package liric.mistaken.config

object Config {
    const val CONFIG_VERSION = "config-version"
    const val CORE_DEBUG = "core.debug"
    const val CORE_LANGUAGE = "core.language"
    const val CORE_MIN_PLAYERS = "core.min-players"
    const val CORE_PERSISTENCE_KEY = "core.persistence-key"
    const val DISCORD_WEBHOOKS_ALERTS = "discord.webhooks.alerts"
    const val DISCORD_WEBHOOKS_GAME_TRACKER = "discord.webhooks.game-tracker"
    const val GAMEPLAY_KILLER_DAMAGE = "gameplay.killer.damage"
    const val GAMEPLAY_KILLER_HEALTH = "gameplay.killer.health"
    const val GAMEPLAY_REWARDS_KILL = "gameplay.rewards.kill"
    const val GAMEPLAY_REWARDS_WIN_KILLER = "gameplay.rewards.win-killer"
    const val GAMEPLAY_REWARDS_WIN_SURVIVOR = "gameplay.rewards.win-survivor"
    const val MESSAGES_ALREADY_COMPLETED = "messages.already-completed"
    const val MESSAGES_FAIL_CLICK = "messages.fail-click"
    const val MESSAGES_NO_KILLER = "messages.no-killer"
    const val MESSAGES_PREFIX = "messages.prefix"
    const val MESSAGES_SUCCESS = "messages.success"
    const val PROXY_ARENA_SERVER = "proxy-arena-server"
    const val PROXY_LOBBY_SERVER = "proxy-lobby-server"
    const val SERVER_MODE = "server-mode"
    const val SETTINGS_GENERATOR_BLOCK = "settings.generator-block"
    const val SETTINGS_LOBBY_PITCH = "settings.lobby.pitch"
    const val SETTINGS_LOBBY_WORLD = "settings.lobby.world"
    const val SETTINGS_LOBBY_X = "settings.lobby.x"
    const val SETTINGS_LOBBY_Y = "settings.lobby.y"
    const val SETTINGS_LOBBY_YAW = "settings.lobby.yaw"
    const val SETTINGS_LOBBY_Z = "settings.lobby.z"
    const val SETTINGS_REPAIR_AMOUNT = "settings.repair-amount"
    const val SETTINGS_REWARDS_COMMANDS = "settings.rewards.commands"
    const val SETTINGS_SOUNDS_COMPLETE = "settings.sounds.complete"
    const val SETTINGS_SOUNDS_MEMORY_HIDE = "settings.sounds.memory-hide"
    const val SETTINGS_SOUNDS_MEMORY_SHOW = "settings.sounds.memory-show"
    const val SETTINGS_SOUNDS_REPAIR = "settings.sounds.repair"
    const val STAMINA_EXHAUSTION_SLOWNESS_LEVEL = "stamina.exhaustion-slowness-level"
    const val STAMINA_LOSS_KILLER = "stamina.loss-killer"
    const val STAMINA_LOSS_SURVIVOR = "stamina.loss-survivor"
    const val STAMINA_RECOVERY_RATE = "stamina.recovery-rate"
    const val TIMERS_ENDING = "timers.ending"
    const val TIMERS_INGAME = "timers.ingame"
    const val TIMERS_STARTING = "timers.starting"
    const val TIMERS_VOTING = "timers.voting"
    const val VISUALS_BOSSBAR_STYLE = "visuals.bossbar-style"
    const val VISUALS_VOTE_FORMAT = "visuals.vote-format"
}
