config-version: 1
core:
  language: es
  min-players: 2
  persistence-key: selected_assassin
  debug: false
timers:
  voting: 30
  starting: 15
  ingame: 300
  ending: 15
discord:
  webhooks:
    game-tracker: URL_AQUI
    alerts: URL_AQUI
  messages:
    waiting-players: Esperando jugadores...
    nobody-escaped: Nadie escapó...
    start:
      title: 🎮 ¡JUEGO INICIADO!
      map-field: 🗺️ Mapa
      mode-field: 🕹️ Modo
      killer-field: 🩸 Killer
      survivors-field: 👥 Survivors
      footer: Mistaken Tracking • LIRIC-MISTAKEN 2.0
    end:
      title: 🏁 ¡PARTIDA TERMINADA!
      result-text: 'Resultado:'
      map-field: 🗺️ Mapa
      winner-field: 🏆 Ganador
      survived-field: 🚪 Sobrevivieron
      footer: Mistaken Tracking • Sesión finalizada
server-mode: MULTIARENA
proxy-lobby-server: lobby
proxy-arena-server: arenas
stamina:
  loss-survivor: 1.0
  loss-killer: 2.0
  recovery-rate: 1.5
  exhaustion-slowness-level: 1
gameplay:
  killer:
    damage: 2.9
    health: 200.0
  rewards:
    kill: 50.0
    win-killer: 500.0
    win-survivor: 200.0
visuals:
  bossbar-style: SOLID
  vote-format: <white>{map}</white> - <yellow>({votes})</yellow><newline>
database:
  type: h2
  mysql:
    host: localhost
    port: 3306
    database: mistaken
    username: root
    password: ''
  postgresql:
    host: localhost
    port: 5432
    database: mistaken
    username: postgres
    password: ''
  pool:
    maximum-pool-size: 10
    minimum-idle: 2
    max-lifetime: 1800000
    connection-timeout: 30000
music:
  enabled: true
  volume: 0.3
  pitch: 1.0
  playlist:
  - id: mistaken:charliehere
    duration: 149
  - id: mistaken:1
    duration: 125
  - id: mistaken:2
    duration: 123
  - id: mistaken:apple
    duration: 155
  - id: mistaken:you
    duration: 182
  - id: mistaken:candy
    duration: 150
generator-block: RAW_IRON_BLOCK
repair-amount: 10
rewards:
  commands:
  - eco give %player% 500
  - msg %player% &a&l[!] &fHas recibido &6500 monedas &fpor tu trabajo.
sounds:
  repair: BLOCK_ANVIL_USE
  complete: UI_TOAST_CHALLENGE_COMPLETE
  memory-show: BLOCK_NOTE_BLOCK_HARP
  memory-hide: BLOCK_NOTE_BLOCK_CHIME
messages:
  prefix: '<blue><bold>[Mistaken-Gen]</bold></blue> '
  already-completed: <green>This generator is already at 100%!
  no-killer: <red><bold>[!]</bold> Killers cannot repair, your mission is to hunt!
  success: <green><bold>[!]</bold> <white>Generator successfully powered! You received
    your rewards.
  fail-click: <red><bold>[!]</bold> <white>Fake ingot! Progress dropped by 10%.
settings:
  lobby:
    world: Mistaken
    x: 317.49091333512126
    y: 54.0
    z: 153.5797921360857
    yaw: 2.069739
    pitch: 4.7378817
  flashlight:
    range: 8.0
    points: 3
    viewer-radius: 32.0
nametags:
  ingame:
    lines:
    - "%color%%name%"
    - "<red>HP: %health%"
    size: 1.0
    background-color: "0,0,0,0"
    shadow: true
  global:
    lines:
    - "<gray>%name%"
    size: 1.0
    background-color: "0,0,0,0"
    shadow: false
animations:
  killer:
    ataque: ataque
    run: run
    walk: walk
    jump: jump
    idle: estiramiento
    stun: stun
  survivor:
    ataque: ataque
    run: run
    walk: walk
    jump: jump
    idle: estiramiento
    stun: stun
  slasher:
    ataque: slasher_ataque
    run: slasher_run
    walk: slasher_walk
    jump: slasher_jump
    idle: slasher_idle
    stun: stun
  colorandelectricity:
    ataque: ataque_asesino_3
    run: crawl
    walk: killer_walk_default
    jump: slasher_jump
    idle: slasher_idle
    stun: stun
