name: Mistaken
version: '${version}'
main: liric.mistaken.Mistaken
loader: liric.mistaken.MistakenPluginLoader
api-version: '1.21'
author: Pumpkingz
folia-supported: true

dependencies:
  server:
    ArenaAPI:
      load: BEFORE
      required: false
      join-classpath: true
    Meowtils:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    ExcellentEconomy:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    CraftEngine:
      load: BEFORE
      required: false
    Parties:
      load: BEFORE
      required: false
    packetevents:
      load: BEFORE
      required: true
    ObserverPaper:
      load: BEFORE
      required: false
    LodestoneParties:
      load: BEFORE
      required: false
    Nexo:
      load: BEFORE
      required: false
    ItemsAdder:
      load: BEFORE
      required: false
    Oraxen:
      load: BEFORE
      required: false
