name: MistakenDeluxe-Visual-Addon
version: '${version}'
main: liric.mistaken.visual.VisualAddon
api-version: '1.21'
dependencies:
  server:
    Mistaken:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    MiniPlaceholders:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
